<?php

namespace Database\Factories;

class SchoolFakerProvider extends \Faker\Provider\Base
{

    protected static $schoolNames = [
        'San Blas',
        'El Alamo',
        'Antonio De Nebrija',
        'Cardenal Cisneros',
        'Cervantes',
        'Daoiz Y Velarde',
        'Sagrado Corazon De Jesus',
        'San Felipe Neri',
        'Escuelas Pias',
        'Emperador Fernando',
        'Santa Maria De La Providencia',
        'Complutense',
        'Nuestra Señora Del Val',
        'Doctora De Alcala',
        'San Gabriel',
        'San Ignacio De Loyola',
        'Minerva',
        'Alonso De Avellaneda',
        'Calasanz',
        'Lope De Vega',
        'Antonio Machado',
        'Infanta Catalina',
        'Federico Garcia Lorca',
        'Antonio Machado',
        'San Pedro Apostol',
        'San Antonio',
        'Juan Xxiii',
        'Liceo Europeo',
        'Francisco Giner De Los Rios',
        'Daoiz Y Velarde',
        'Bienaventurada Virgen Maria',
        'Colegio Suizo De Madrid (Suizo)',
        'Carmen Conde',
        'Nuestra Señora De Rihondo',
        'Santisima Trinidad',
        'Nuestra Señora De Los Remedios',
        'Amor De Dios',
        'La Inmaculada',
        'Virgen Del Remedio',
        'Centro Educativo Villa De Alcorcon',
        'Daniel Martin',
        'Parroco D. Victoriano',
        'San Pablo-Ceu',
        'Nuestra Señora De Fatima',
        'Obispo Moscoso',
        'Santa Quiteria',
        'San Jose De Calasanz',
        'Virgen Del Puerto',
        'Sagrada Familia',
        'San Pascual',
        'Vicente Aleixandre',
        'Apostol Santiago',
        'Arco Iris Abastos',
        'Loyola',
        'San Isidro',
        'Domenico Scarlatti',
        'Principe De Asturias',
        'Jorge Manrique',
        'Nuestra Señora De La Milagrosa',
        'El Carrascal',
        'San Juan Bautista',
        'El Torreon',
        'Juan Ramon Jimenez',
        'Belmonte De Tajo',
        'Principe Don Felipe',
        'Virgen De Europa',
        'Trinity College Boadilla',
        'San Sebastian',
        'Batalla De Brunete',
        'Peñalta',
        'Gsd International School Buitrago',
        'Montelindo',
        'Pico De La Miel',
        'Eugenio Muro',
        'Federico Garcia Lorca',
        'Miguel Delibes',
        'Tome Y Orgaz',
        'Suarez Somonte',
        'Via Romana',
        'Regina Assumpta',
        'Ventura Rodriguez',
        'Juan Carlos I',
        'Virgen Del Consuelo',
        'San Juan De Dios',
        'Villa De Cobeña',
        'Apis Aurelia',
        'Seis De Diciembre',
        'Soledad Sainz',
        'Virgen De Los Remedios',
        'Marques De Santillana',
        'Internacional Pinosierra',
        'Virgen De La Paz',
        'Cañada Real',
        'Santisima Trinidad',
        'Miguel Delibes',
        'Jaime Ferran',
        'Virgen De La Almudena',
        'San Pablo',
        'Mama Juanita',
        'Virgen Del Henar',
        'San Esteban',
        'Miguel Catalan',
        'Nuestra Señora De La Soledad',
        'Hermanos Ortiz De Zarate',
        'Angel Berzal Fernandez',
        'Felipe Ii',
        'Padre Gerardo Gil',
        'Carlos Ruiz',
        'San Esteban',
        'Martina Garcia',
        'Alarilla',
        'Carlos Ruiz',
        'San Gregorio',
        'La Alhondiga',
        'Ortiz Echagüe',
        'Santa Margarita Maria Alacoque',
        'Sagrado Corazon',
        'Liceo Juan De La Cierva I',
        'Mengual',
        'Santa Teresa',
        'Jesus Nazareno',
        'San Jose',
        'San Sebastian',
        'Matematico Puig Adam',
        'La Inmaculada-Padres Escolapios',
        'Divina Pastora',
        'Seseña Y Benavente',
        'Alarnes',
        'San Jose De Calasanz',
        'Ciudad De Madrid',
        'Garcilaso De La Vega',
        'La Salle',
        'Alejandro Rubio',
        'Colegio Juan Pablo Ii Y La Inmaculada',
        'Villa De Guadarrama',
        'Virgen De La Encina',
        'Hermanos Tora',
        'Calderon De La Barca',
        'Lepanto',
        'Marques De Leganes',
        'La Inmaculada',
        'Liceo San Pablo',
        'El Salvador',
        'Gonzalo De Berceo',
        'Victor Pradera',
        'Miguel De Cervantes',
        'Ortega Y Gasset',
        'Aben Hazam',
        'Jose De Churriguera',
        'Luis Vives',
        'Maria Zambrano',
        'Duque De Alba',
        'Montfort International School',
        'Cervantes',
        'Damaso Alonso',
        'Cervantes Baby',
        'Francisco Alcantara Ceramica',
        'Isaac Albeniz',
        'Ciudad De Jaen',
        'Vasco Nuñez De Balboa',
        'Escuelas Aguirre',
        'Agustina Diez',
        'Alberto Alcocer',
        'Alfonso X El Sabio',
        'Antonio Machado',
        'De Practicas Asuncion Rincon',
        'Azorin',
        'Barcelona',
        'Beata Maria Ana De Jesus',
        'Bolivia',
        'Escuelas Bosque',
        'Capitan Cortes',
        'Cervantes',
        'Ciudad De Los Angeles',
        'Ciudad Pegaso',
        'Claudio Moyano',
        'Conde De Romanones',
        'Cristobal Colon',
        'Divino Corazon',
        'Emilia Pardo Bazan',
        'Francisco Fatou',
        'Francisco De Quevedo',
        'Francisco Ruano',
        'Fray Junipero Serra',
        'Fray Pedro Ponce De Leon',
        'Reina Victoria',
        'Gonzalo Fernandez De Cordoba',
        'Gustavo Adolfo Becquer',
        'Haiti',
        'Hermanos Pinzon',
        'Hernan Cortes',
        'Honduras',
        'Hospital Del Niño Jesus',
        'Maria Soriano',
        'Isaac Peral',
        'Luis Bello',
        'Jaime Balmes',
        'Javier De Miguel',
        'Joaquin Dicenta',
        'Jose Maria De Pereda',
        'Jovellanos',
        'Juan De La Cierva',
        'Juan Ramon Jimenez',
        'Juan Sebastian Elcano',
        'Lopez Vicuña',
        'Luis De Gongora',
        'Manuel De Falla',
        'Colegio Diocesano Maria Inmaculada - Mogambo',
        'Colegio Diocesano Maria Inmaculada - Joaquin Turina',
        'Colegio Diocesano Maria Inmaculada - Luis Ruiz',
        'Jorge Manrique',
        'Marques De Marcenado',
        'Mater Amabilis',
        'Amos Acero',
        'Mejico',
        'Mendez Nunez',
        'Menendez Y Pelayo',
        'Menendez Pidal',
        'Mesonero Romanos',
        'Navas De Tolosa',
        'Eduardo Rojo',
        'Nuestra Señora De La Concepcion',
        'Padre Coloma',
        'Padre Mariana',
        'Padre Piquer',
        'Padre Poveda',
        'Parque Aluche',
        'Peru',
        'Pinar Del Rey',
        'Pio Xii',
        'Puerto Rico',
        'Gonzalo De Berceo',
        'Ramiro De Maeztu',
        'Regimiento Inmemorial Del Rey',
        'Republica Del Brasil',
        'Republica Dominicana',
        'Republica De Ecuador',
        'Republica Del Paraguay',
        'Republica Del Uruguay',
        'Republica De Venezuela',
        'Los Rosales',
        'Rufino Blanco',
        'Sagunto',
        'San Carlos',
        'San Eugenio Y San Isidro',
        'San Ignacio De Loyola',
        'San Ildefonso',
        'San Isidoro',
        'San Juan De La Cruz',
        'San Pablo',
        'Santa Ana Y San Rafael',
        'Santa Maria',
        'Santo Domingo',
        'Tirso De Molina',
        'La Alameda',
        'Vedruna',
        'Arcipreste De Hita',
        'Alameda De Osuna',
        'El Ave Maria',
        'Beata Filipina-Fund.Feliciana Viertola',
        'Eipa Escuela Infantil Parque De Las Avenidas',
        'Comendadoras De Santiago',
        'Madres Concepcionistas',
        'Cristo Rey',
        'Cristo Rey',
        'Luz Casanova Embajadores',
        'Nazaret-Oporto',
        'Sagrado Corazon De Jesus',
        'Colegio Nuevo Equipo',
        'San Luis-Felca',
        'Fundacion Caldeiro',
        'Hastings School (Britanico)',
        'Jesus Maestro',
        'Jesus Maria',
        'Direccion Area Territorial Madrid-Capital',
        'Madre De Dios',
        'Maria Inmaculada',
        'Maria Reina',
        'Maria Reina',
        'Mater Clementissima',
        'Mater Inmaculata',
        'Direccion Area Territorial Madrid-Oeste',
        'La Merced',
        'Mirasierra',
        'Blanca De Castilla',
        'Nuestra Señora Del Buen Consejo',
        'Nuestra Señora Del Buen Consejo',
        'Nuestra Señora De Los Dolores',
        'Nuestra Señora De Fatima',
        'Nuestra Señora De Las Maravillas',
        'Obra So.N.S.Montserrat-S.Simon Y S.Judas',
        'Direccion Area Territorial Madrid-Este',
        'Nuestra Señora De Las Nieves',
        'Nuestra Señora De La Paz',
        'Nuestra Señora Del Pilar',
        'Nuestra Señora Del Pilar',
        'Liceo Oroquieta',
        'El Osito De Luis De Larrainza',
        'El Porvenir',
        'El Prado',
        'Purisima Concepcion',
        'Ramon Y Cajal',
        'Reina De Los Angeles',
        'El Ardal',
        'Sagrado Corazon',
        'Sagrado Corazon',
        'Sagrado Corazon',
        'Santa Maria Micaela',
        'La Salle-Sagrado Corazon',
        'Sagrados Corazones',
        'Enriqueta Aymer',
        'San Antonio',
        'San Buenaventura',
        'Arturo Soria',
        'San Eulogio',
        'San Jaime Apostol',
        'San Javier',
        'San Jose',
        'San Jose',
        'Instituto San Jose',
        'San Jose De Cluny',
        'San Juan Bautista',
        'Direccion Area Territorial Madrid-Sur',
        'San Rafael Arcangel-Santa Luisa',
        'San Roque',
        'San Viator',
        'San Vicente',
        'Santa Elizabeth',
        'Santa Gema Galgani',
        'Real Colegio Santa Isabel-La Asuncion',
        'Santa Maria',
        'Santa Maria De Los Apostoles',
        'Santa Maria Del Pilar',
        'Santa Maria De Los Pinos',
        'Santa Maria Del Valle Cep',
        'Colegio Escuelas Santisimo Sacramento',
        'Santisimo Sacramento',
        'Santo Angel De La Guarda',
        'Santo Angel De La Guarda',
        'Teide Iv',
        'Virgen De Begoña',
        'Virgen Del Pilar',
        'Colegio A La Par',
        'Portugal',
        'Tomas Breton',
        'Amador De Los Rios',
        'Aravaca',
        'Asuncion Cuestablanca',
        'Santa Rafaela Maria',
        'Carlos V',
        'Carmen Cabezuelo',
        'Concepcion Arenal',
        'Doctor Conde Arruga',
        'Costa Rica',
        'Cuba',
        'Divino Maestro',
        'Doctor Federico Rubio',
        'Ermita Del Santo',
        'Felipe Ii',
        'Fernandez Moratin',
        'Fernando El Catolico',
        'Francisco De Luis',
        'Garcia Morente',
        'Pi I Margall',
        'Francisco De Goya',
        'Isabel La Catolica',
        'Joaquin Costa',
        'Jose Calvo Sotelo',
        'Legado Crespo',
        'Lepanto',
        'Lope De Vega',
        'Manuel Bartolome Cossio',
        'Manuel Sainz De Vicuña',
        'Marcelo Usera',
        'Miguel Blasco Vilatela',
        'Miguel De Unamuno',
        'Manuel Nuñez De Arenas',
        'Antonio Moreno Rosales',
        'Nuestra Señora De La Almudena',
        'Leopoldo Alas',
        'Palacio Valdes',
        'Republica De Panama Nº 1',
        'Patriarca Obispo Eijo Garay',
        'Ramon Gomez De La Serna',
        'Real Armada',
        'Republica De Colombia',
        'Republica De Chile',
        'Republica De El Salvador',
        'San Cristobal',
        'San Juan Bosco',
        'Vazquez De Mella',
        'Afuera Iii A',
        'Patrocinio De Maria',
        'Amor De Dios',
        'Amor Misericordioso',
        'Amoros',
        'Arcangel',
        'Santa Beatriz De Silva',
        'Cardenal Spinola',
        'El Carmelo Teresiano',
        'Central',
        'Liceo Sorolla B',
        'Ciudad De Los Muchachos',
        'Liceo Consul',
        'Corazon Inmaculado',
        'Corazon De Maria',
        'Ciudad De Cordoba',
        'Decroly',
        'Divina Pastora',
        'Colegio Institucion Del Divino Maestro',
        'Trilema Avenida America',
        'Fem School',
        'Tajamar',
        'Montpellier',
        'Santa Maria De La Hispanidad',
        'Fray Luis De Leon',
        'Gamo Diana',
        'Los Robles',
        'Hispano Aleman',
        'La Inmaculada-Marillac',
        'British Council School (Britanico)',
        'Alenta',
        'Jesus Maria',
        'Jardin Kinderland',
        'Luz Casanova',
        'Luz Casanova',
        'Salesianos Atocha',
        'Maria Corredentora',
        'Maria Cristina',
        'Maria Reina',
        'Marin Amat',
        'Menesiano',
        'Madres Mercedarias De D. Juan De Alarcon',
        'La Milagrosa',
        'Minerva',
        'Montealto',
        'Natividad De Nuestra Señora',
        'Nuestra Señora De Los Angeles',
        'Asuncion-Vallecas',
        'Nuestra Señora Del Carmen',
        'Colegio La Milagrosa',
        'Nuestra Señora De La Consolacion',
        'Nuestra Señora De Las Escuelas Pias',
        'Calasancio Nuestra Señora De Las Escuelas Pias',
        'Nuestra Señora De Las Escuelas Pias',
        'Nuestra Señora De Gracia',
        'Liceo Madariaga',
        'Real Colegio Nuestra Señora De Loreto',
        'Nuestra Señora De La Merced',
        'Nuestra Señora De La Merced',
        'Nuestra Señora De La Merced',
        'Montserrat',
        'Nuestra Señora De La Paloma',
        'Nuestra Señora Del Recuerdo',
        'Huerfanos De La Armada',
        'Wisdom School Madrid',
        'Nuestra Señora Del Sagrado Corazon',
        'Nuestra Señora Santa Maria',
        'Nuestra Señora De Las Victorias',
        'Nuestra Señora De Las Victorias',
        'Patrocinio De San Jose',
        'Pureza De Maria',
        'Rafaela Ybarra',
        'Raimundo Lulio',
        'Trilema Safa',
        'Sagrada Familia',
        'Sagrada Familia De Urgel',
        'Sagrado Corazon',
        'Sagrado Corazon De Jesus',
        'Sagrado Corazon De Jesus',
        'Sagrados Corazones',
        'Paraiso Sagrados Corazones',
        'Colegio La Salle San Rafael',
        'La Salle',
        'San Alfonso',
        'El Espinillo ',
        'San Fermin',
        'San Francisco De Asis',
        'San Jose',
        'San Jose De Begoña',
        'San Jose Del Parque',
        'Colegio Aleman De Madrid (Aleman)',
        'Salesianos Paseo De Extremadura',
        'San Patricio',
        'San Pedro',
        'San Roque',
        'Santa Catalina De Sena',
        'Santa Francisca Javier Cabrini',
        'Santa Isabel',
        'Fundacion Santamarca',
        'Santa Maria Del Bosque',
        'Santa Maria Del Carmen',
        'Santa Maria De Los Rosales',
        'Santa Rita',
        'San Gabriel',
        'Santo Angel',
        'Santo Domingo',
        'Santo Domingo Savio',
        'Colegio Senara',
        'Vedruna',
        'Virgen De Atocha',
        'Colegio Virgen De Mirasierra',
        'Colegio San Pedro Apostol',
        'Centro Cultural Elfo',
        'Stella Maris',
        'Colegio Santa Maria Del Camino',
        'Colegio Internacional Nicoli',
        'Claret',
        'Liceo Iberico',
        'Agrupacion Escolar Europa',
        'San Agustin',
        'Valdeluz',
        'Cumbre-Oxford',
        'Azorin',
        'Nuestra Señora De La Providencia',
        'Nuestra Señora De La Estrella',
        'Obispo Perello',
        'Valdebernardo',
        'El Cid',
        'Divina Pastora',
        'Inmaculada Concepcion',
        'Los Lapazares',
        'Reinado Del Corazon De Jesus',
        'Sagrado Corazon',
        'Centro Cultural Salmantino',
        'San Alberto Magno',
        'Colegio Nuestra Señora De Loreto Fesd',
        'Mater Purissima',
        'Los Alamos',
        'Los Pinos',
        'Siglo Xxi',
        'Nebrija-Rosales',
        'Liceo Versalles',
        'San Jose',
        'San Jose',
        'Santa Cruz',
        'Union Chretienne De St.Chaumond (Franc.)',
        'Nuestra Señora Del Pilar',
        'San Martin',
        'Parque Conde De Orgaz',
        'Agora',
        'Santa Teresa De Jesus',
        'Santamarca',
        'Santa Engracia',
        'Catedra De Pediatria, Hospital Clinico',
        'Ortega Y Gasset',
        'Alcalde De Mostoles',
        'Amadeo Vives',
        'Instituto Politecnico N.1 Del Ejercito',
        'Emilio Castelar',
        'Doctor Tolosa Latour',
        'Arcipreste De Hita',
        'San Cristobal De Los Angeles',
        'Carlos Maria Rodriguez De Valcarcel',
        'Martinez Montañes',
        'Ciudad De Guadalajara',
        'Afuera Ii',
        'Gonzalez Cañadas',
        'Ciudad De Zaragoza',
        'San Bernardo',
        'Aries',
        'Diaz Balaguer',
        'Joaquín Turina',
        'Vox',
        'Estudio',
        'Centro Cultural Palomeras',
        'La Inmaculada',
        'Maria Inmaculada',
        'El Lago',
        'Fec Santa Joaquina De Vedruna',
        'San Fernando',
        'Francisco Arranz',
        'Ciudad De Badajoz',
        'Tirso De Molina',
        'San Miguel',
        'Nuestra Señora De Los Dolores',
        'San Benito',
        'San Ramon Y San Antonio',
        'Altair, Colegio Internacional',
        'Maria Virgen',
        'Agustiniano',
        'Lope De Vega',
        'Dario Estudio',
        'Barajas',
        'Centro De Estudios Castilla',
        'Santa Barbara',
        'La Salle-La Paloma-Fundacion Lara',
        'Bristol',
        'Sagrado Corazon',
        'Gregorio Marañon',
        'Chamberi',
        'Casa De La Virgen',
        'San Jose-Lucero',
        'Barrio Simancas',
        'Lourdes',
        'Mater Salvatoris',
        'Virgen De La Paloma',
        'Escuela Profesional Javeriana',
        'Santa Maria Del Yermo',
        'Maria Auxiliadora',
        'Colegio Ceu San Pablo De Claudio Coello',
        'Juan Zaragueta',
        'Conde De Orgaz',
        'Carlos Iii',
        'San Blas',
        'Gómez Moreno',
        'Rey Pastor',
        'Vallecas I',
        'Carlos Sainz De Los Terreros',
        'Ciudad De Valencia',
        'Enrique Tierno Galvan',
        'Pio Baroja',
        'Parque Aluche',
        'Eijo Y Garay',
        'Nuestra Señora Del Lucero',
        'Nuestra Señora De La Almudena',
        'Tetuan De Las Victorias',
        'Cardenal Herrera Oria',
        'Lorenzo Luzuriaga',
        'Beatriz Galindo',
        'Isabel La Catolica',
        'Juan De La Cierva',
        'Cardenal Cisneros',
        'San Isidro',
        'Emperatriz Maria De Austria',
        'Calderon De La Barca',
        'Vista Alegre',
        'Pintor Rosales',
        'Jorge Guillen',
        'C.R.E. Antonio Vicente Mosquete',
        'Colegio Madrid Pinar',
        'Arquitecto Gaudi',
        'Marques De Suanzes',
        'Princesa Sofia',
        'Francisco Del Pozo',
        'Fundacion Goyeneche',
        'Antonio De Nebrija',
        'Pacifico',
        'Filosofo Seneca',
        'Joaquin Turina',
        'Concha Espina',
        'Rabindranath Tagore',
        'Bravo Murillo',
        'La Palma',
        'Luis Cernuda',
        'Esperanza',
        'Doctor Severo Ochoa',
        'Pio Baroja',
        'Daniel Vazquez Diaz',
        'Jose Ortega Y Gasset',
        'Palomeras Vallecas',
        'Garcia Morato',
        'Gran Capitán',
        'Afuera I',
        'Monseñor Alves Bras',
        'La Anunciata',
        'Bernadette',
        'Guzman El Bueno',
        'Centro Nuevo De Pedagogia',
        'Cumbre',
        'Estudio 3',
        'Lycee Français (Frances)',
        'La Inmaculada',
        'Mirasol',
        'La Natividad',
        'Los Olmos',
        'Las Naciones',
        'Carmen Martin Gaite',
        'Santa Monica',
        'Teide Ii',
        'Trabenco',
        'Vida',
        'Bienaventurada Virgen Maria',
        'Buenafuente',
        'Institucion Profesional Salesiana',
        'Nervion',
        'Nuestra Señora De Fatima',
        'Primero De Mayo',
        'Cervantes',
        'Colegio De Jesus',
        'Jose Ramon Otero',
        'Nuestra Señora De Las Delicias',
        'Ciudad Escolar',
        'San Pio X',
        'Virgen De Lourdes',
        'Maria Auxiliadora',
        'Virgen De La Peña Sacra',
        'San Sebastian',
        'Jarama',
        'Vicente Aleixandre',
        'San Pablo',
        'Nuestra Señora Del Remolino',
        'Divino Maestro',
        'Santa Teresa',
        'San Miguel Arcangel',
        'Claudio Vazquez',
        'Andres Torrejon',
        'Beato Simon De Rojas',
        'Liceo Villa Fontana',
        'Villa De Mostoles',
        'Balmes',
        'La Inmaculada',
        'Antonio Hernandez',
        'Juan Perez Villaamil',
        'Colegio Villaeuropa',
        'Antusana',
        'Federico Garcia Lorca',
        'Felipe Trigo',
        'Nuestra Señora Del Carmen',
        'Principe De Asturias',
        'Carlos Ruiz',
        'San Luis Gonzaga',
        'Carmen Martin Gaite',
        'Isabel La Catolica',
        'Internacional Eurovillas',
        'Juan De Goyeneche',
        'Virgen De La Ribera Fund. Hnos.',
        'Ciudad De Merida',
        'Magerit',
        'Virgen Del Carmen',
        'Nuestra Señora Del Castillo',
        'Isabel La Catolica',
        'El Prado',
        'Nuestra Señora De La Providencia',
        'Sagrada Familia',
        'Santo Domingo De Silos',
        'Los Angeles',
        'Asuncion De Nuestra Señora',
        'Retamar',
        'San Jose De Cluny',
        'Hogar Del Buen Consejo',
        'San Luis De Los Franceses',
        'Divino Maestro',
        'Gil Gayarre',
        'Gerardo Diego',
        'San Jose Obrero',
        'Instituto Veritas',
        'Escuelas Pias De San Fernando',
        'Everest',
        'Liceo Sorolla C',
        'Enrique De Mesa',
        'Las Cigüeñas',
        'Nuestra Señora De Navahonda',
        'San Jose',
        'Fundacion Colegio Berriz',
        'Cristo Rey',
        'Institucion Educativa Logos',
        'Santa Maria De Las Rozas',
        'Virgen De Navalazarza',
        'Vega Del Jarama',
        'Villar Palasi',
        'Ciudades Unidas',
        'Colegio-Escolania Santo Domingo De Silos',
        'San Lorenzo',
        'La Inmaculada Concepcion',
        'Real Colegio Alfonso Xii',
        'General Izquierdo',
        'San Marcos',
        'Virgen De La Nueva',
        'Francisco Carrillo',
        'Mi Cole',
        'Nuestra Señora De Valvanera',
        'Silvio Abad',
        'Joan Miro',
        'Colegio Internacional Sek-Ciudalcampo',
        'Duque De Rivas',
        'Virgen Del Rosario',
        'El Pilar',
        'Carlos Ruiz',
        'Virgen Del Rosario',
        'El Buen Gobernador',
        'Gabriel Y Galan',
        'San Juan Bosco',
        'Alba',
        'Miguel De Cervantes',
        'La Gaviota',
        'San Juan Evangelista',
        'J.A.B.Y.',
        'Isaac Peral',
        'Las Veredillas',
        'San Jose',
        'Nuestra Señora Del Pilar',
        'Alto Jarama',
        'Cardenal Cisneros',
        'San Ignacio De Loyola',
        'Los Angeles',
        'Nuestra Señora De Lourdes',
        'Nuestra Señora Del Rosario',
        'Angel Castro',
        'Juan Falco',
        'Cristo De La Salud',
        'Arzobispo Morcillo',
        'San Jose',
        'Marques De Vallejo',
        'Vicente Aleixandre',
        'Samer Calasanz',
        'Ramon Linacero',
        'Jesus Aramburu',
        'Miguel De Cervantes',
        'Valdemera',
        'Concepcion Garcia Robles',
        'Nuestra Señora De La Poveda',
        'Gregorio Canella',
        'San Damaso',
        'Santiago Apostol',
        'Colegio Internacional Sek-El Castillo',
        'San Lucas',
        'Nuestra Señora De La Victoria',
        'Santa Elena',
        'Nuestra Señora De La Victoria De Lepanto',
        'Hermanos Garcia Noblejas',
        'Colegio Alcala',
        'San Jose De Valderas',
        'San Andres',
        'Felipe Ii',
        'Ciudad De Getafe',
        'Inglan',
        'Instituto Radio Television Española (Instituto Rtve)',
        'Projardin Retiro',
        'Los Castillos',
        'Ramon Maria Del Valle Inclan',
        'Nuestra Señora De La Fuencisla',
        'Ignacio Zuloaga',
        'Virgen Del Cerro',
        'Fontarron',
        'Vicente Aleixandre',
        'Principe Felipe',
        'Ramon Perez De Ayala',
        'Los Castillos',
        'Dos Parques',
        'Cuna De Jesus',
        'Joyfe',
        'Tirso De Molina',
        'Los Angeles',
        'Amanecer',
        'Santo Domingo',
        'Cervantes',
        'Juan Gris',
        'Giner De Los Rios',
        'Severo Ochoa',
        'Vicente Aleixandre',
        'Kensington School (Britanico)',
        'Gabriel Y Galan',
        'Universidad Politecnica De Madrid',
        'Universidad Autonoma De Madrid',
        'Universidad Complutense De Madrid',
        'Universidad De Alcala De Henares',
        'San Juan Garcia',
        'Maria Inmaculada',
        'Vicente Ferrer',
        'Jesus Varela',
        'Daniel Vazquez Diaz',
        'Pardo Bazan',
        'Perez Galdos',
        'Pio Baroja',
        'El Olivar',
        'Ramon Y Cajal',
        'San Alonso De Orozco',
        'Arquitecto Pedro Gumiel',
        'Parque De Lisboa',
        'Torres Quevedo',
        'Maria Moliner',
        'Andres Manjon',
        'Dionisio Aguado',
        'Doctor Severo Ochoa',
        'Butarque',
        'Pasamonte',
        'Avenida De Los Toreros',
        'Mariano Jose De Larra',
        'La Estrella',
        'San Juan Bautista',
        'Jaime Vera',
        "Pipo's",
        'Adela Abrines Castaños',
        'Ciudad De Parla',
        'Rosalia De Castro',
        'Rio Bidasoa',
        'Manuel De Falla',
        'Las Rozas I',
        'Nuestra Señora De La Esperanza',
        'Gonzalo Torrente Ballester',
        'Andal Alameda',
        'Nuestra Señora De Loreto',
        'Ramiro De Maeztu',
        'Juan De Herrera',
        'Beatriz Galindo',
        'Dulcinea',
        'Juan De Austria',
        'Santos Niños',
        'Emilio Casado',
        'Santiago Ramon Y Cajal',
        'Vicente Aleixandre',
        'Francisco De Quevedo',
        'Lope De Vega',
        'Dionisio Ridruejo',
        'Las Cumbres',
        'Juan Ramon Jimenez',
        'Andal',
        'Principe De Asturias',
        'Meseta De Orcasitas',
        'Luis Feito',
        'San Miguel',
        'Palomeras Bajas',
        'Vallecas',
        'Seminario Arzobispal La Inmaculada Y San Damaso',
        'Arcangel Rafael',
        'Salzillo-Valle Inclan',
        "King's College",
        'Sagrado Corazon Reparadoras',
        'San Fernando',
        'Santa Teresa De Jesus',
        'Miguel Hernandez',
        'Francisco De Quevedo',
        'Inmaculada Concepcion',
        'Miguel De Cervantes',
        'Leo Kanner',
        'Los Peñascales',
        'Colegio Escandinavo (Sueco)',
        'Hof Der Lage Landen (Paises Bajos)',
        'Numont School (Britanico)',
        'Ecole Saint-Exupery (Frances)',
        'Lycee Moliere (Frances)',
        'Gonzalo De Berceo',
        'Menendez Pidal',
        'Buenos Aires',
        'American School Of Madrid (Ee.Uu.)',
        'The English Montessori School (Britanico)',
        'International School Of Madrid (Britan.)',
        'Parque',
        'Casa De La Cultura',
        'Cultural Moratalaz',
        'Aluche',
        'Fortuny',
        'Ciudad De Los Poetas',
        'Ramon Y Cajal',
        'Miguel Delibes',
        'Celestino Mutis',
        'Damaso Alonso',
        'Cardenal Herrera Oria',
        'Agustina De Aragon',
        'Humanejos',
        'Leon Felipe',
        'Scuola Statale Italiana De Madrid (Italiano)',
        'Prado De Santo Domingo',
        'Nuestra Señora De Moratalaz',
        'Nazaret',
        'Manuel Azaña',
        'Iplacea',
        'Mariano Benlliure',
        'Antonio Machado',
        'Federico Garcia Lorca',
        'Pradolongo',
        'Vicalvaro',
        'San Sebastian',
        'Ciudad Del Aire',
        'San Juan Bautista',
        'Arturo Soria',
        'San Miguel Ii',
        'La Purisima',
        'Fomento-Fundacion',
        'K.S.',
        'Valdepalitos',
        'Federico Garcia Lorca',
        'Federico Garcia Lorca',
        'Mateo Aleman',
        'Galileo Galilei',
        'Blas De Otero',
        'San Mateo',
        'Mariana Pineda',
        'Vallecas-Magerit',
        'Las Musas',
        'Barrio De Bilbao',
        'Leonardo Da Vinci',
        'Moratalaz',
        'Miguel Hernandez',
        'Luis De Gongora',
        'Gerardo Diego',
        'Miguel Servet',
        'Breogan',
        'Virgen Del Cortijo',
        'Ciudad De Roma',
        'La Latina',
        'Blas De Otero',
        'Pinar Prados De Torrejon',
        'Leon Felipe',
        'Fuentesanta',
        'Aula 3',
        'Mariano Jose De Larra',
        'Pablo Picasso',
        'Arlequin',
        'Celso Emilio Ferreiro',
        'Francisco De Quevedo',
        'Jose Maria De Pereda',
        'Julian Besteiro',
        'Antonio Machado',
        'Felipe Iv',
        'Antonio Machado',
        'Antonio Machado',
        'Escuela Superior De Hosteleria Y Turismo',
        'Centro De Formacion Tecnica',
    ];

    /**
     * Un nombre aleatorio de escuelas en España
     * @return string
     */
    public function schoolName()
    {
        return static::randomElement(static::$schoolNames);
    }
}
